name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.4.4
  - pip=20.3.3
  - pandas-profiling=3.2.0
  - pyarrow=8.0.0
  - pip:
      - wandb==0.13.3