name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.0.1
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyterlab=3.0.12
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - matplotlib=3.3.4
  - pandas=1.4.4
  - pyarrow=8.0.0
  - git=2.30.2
  - pip=20.3.3
  - pip:
      - wandb==0.13.3
